---

- hosts: all
  gather_facts: False
  become: yes
  become_method: sudo

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (yum -y update && yum install -y python-minimal)

    - name: Copy id_rsa key to guest
      copy:
        src: /home/marcos/Documents/id_rsa.pub
        dest: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: 0600  
         